language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - pypy

install:
  - pip install -q -r requirements/main.txt
  - pip install -q -r requirements/tests.txt
  - pip install -q -e .

script:
  - py.test tests
